// Code autogenerated by mockery v2.0.0
//
// Do not manually edit the content of this file.

// Package consulapitest contains autogenerated mocks.
package consulapitest

import "github.com/shoenig/consulapi"
import "github.com/stretchr/testify/mock"

// Candidate is an autogenerated mock type for the Candidate type
type Candidate struct {
	mock.Mock
}

// Participate provides a mock function with given fields: mockeryArg0, mockeryArg1
func (mockerySelf *Candidate) Participate(mockeryArg0 consulapi.LeadershipConfig, mockeryArg1 consulapi.AsLeaderFunc) (consulapi.LeaderSession, error) {
	ret := mockerySelf.Called(mockeryArg0, mockeryArg1)

	var r0 consulapi.LeaderSession
	if rf, ok := ret.Get(0).(func(consulapi.LeadershipConfig, consulapi.AsLeaderFunc) consulapi.LeaderSession); ok {
		r0 = rf(mockeryArg0, mockeryArg1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(consulapi.LeaderSession)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(consulapi.LeadershipConfig, consulapi.AsLeaderFunc) error); ok {
		r1 = rf(mockeryArg0, mockeryArg1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
