// Code autogenerated by mockery v2.0.0
//
// Do not manually edit the content of this file.

// Package consulapitest contains autogenerated mocks.
package consulapitest

import "github.com/stretchr/testify/mock"

// LeaderSession is an autogenerated mock type for the LeaderSession type
type LeaderSession struct {
	mock.Mock
}

// Abdicate provides a mock function with given fields:
func (mockerySelf *LeaderSession) Abdicate() error {
	ret := mockerySelf.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Current provides a mock function with given fields:
func (mockerySelf *LeaderSession) Current() (string, error) {
	ret := mockerySelf.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionID provides a mock function with given fields:
func (mockerySelf *LeaderSession) SessionID() string {
	ret := mockerySelf.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
